server:
  port: 8888

# 应用名称
spring:
  application:
    name: haowu
  datasource:
      url: jdbc:mysql://localhost:3306/e-commerce?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  thymeleaf:
    cache: false
  #RabbitMQ
  rabbitmq:
    #服务器
    host: 127.0.0.1
    username: guest
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完后再处理下一条
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，比如配2.0，第一次就等10s，第二次等20s，第三次等40s
        multiplier: 1

  redis:
    #服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    connect-timeout: 10000ms
    lettuce:
      pool:
        #最大连接数：默认8
        max-active: 8
        #最大空闲连接，默认8
        max-wait: 10000ms
        #最小空闲连接，默认8
        max-idle: 200
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 2
      logic-not-delete-value: 1
      logic-delete-field: "status"
      id-type: auto
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: e.commerce.haowu.system.entity
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
